### ISSUE TITLE
Where can I find Signal/TransientDetector.h?

### ISSUE THREAD

**Issue by happyTonakai** [tmdarwen/PhaseVocoder#7]
Hi, Darwen. I've read your blog at this [page](https://www.tmdarwen.com/latest/detecting-audio-transients) and I'm interested in the implementation of the transient detection algorithm. However I can't find the source code you've mentioned. Am I missing something? Looking forward to your response. Thank you.

**Comment by chee** [comment]
hi, @happyTonakai. it's here https://github.com/tmdarwen/AudioLib/blob/a13efa0ce077e0d1f76e32126588a07aa815a1c8/Source/Signal/Source/TransientDetector.cpp
